name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bun
        run: |
          curl https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - run: bun install
      - run: bun wiptest
