name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl https://bun.sh/install | bash
      - run: bun install
      - run: bun wiptest
